/*** Autogenerated by WIDL 11.8 from include/xgame.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __xgame_h__
#define __xgame_h__

/* Forward declarations */

#ifndef __IXGameImpl_FWD_DEFINED__
#define __IXGameImpl_FWD_DEFINED__
typedef interface IXGameImpl IXGameImpl;
#ifdef __cplusplus
interface IXGameImpl;
#endif /* __cplusplus */
#endif

#ifndef __IXGameImpl2_FWD_DEFINED__
#define __IXGameImpl2_FWD_DEFINED__
typedef interface IXGameImpl2 IXGameImpl2;
#ifdef __cplusplus
interface IXGameImpl2;
#endif /* __cplusplus */
#endif

#ifndef __IXGameImpl3_FWD_DEFINED__
#define __IXGameImpl3_FWD_DEFINED__
typedef interface IXGameImpl3 IXGameImpl3;
#ifdef __cplusplus
interface IXGameImpl3;
#endif /* __cplusplus */
#endif

#ifndef __XGameImpl_FWD_DEFINED__
#define __XGameImpl_FWD_DEFINED__
#ifdef __cplusplus
typedef class XGameImpl XGameImpl;
#else
typedef struct XGameImpl XGameImpl;
#endif /* defined __cplusplus */
#endif /* defined __XGameImpl_FWD_DEFINED__ */

/* Headers for imported files */

#include <unknwn.h>
#include <xuser.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __WINESRC__
/*****************************************************************************
 * IXGameImpl interface
 */
#ifndef __IXGameImpl_INTERFACE_DEFINED__
#define __IXGameImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameImpl, 0x973a344e, 0x24bf, 0x4d0f, 0x84,0x57, 0x56,0xc5,0x34,0x89,0x2b,0x29);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("973a344e-24bf-4d0f-8457-56c534892b29")
IXGameImpl : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE XGameGetXboxTitleId(
        UINT32 *titleId) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameImpl, 0x973a344e, 0x24bf, 0x4d0f, 0x84,0x57, 0x56,0xc5,0x34,0x89,0x2b,0x29)
#endif
#else
typedef struct IXGameImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameImpl *This);

    /*** IXGameImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameGetXboxTitleId)(
        IXGameImpl *This,
        UINT32 *titleId);

    END_INTERFACE
} IXGameImplVtbl;

interface IXGameImpl {
    CONST_VTBL IXGameImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameImpl methods ***/
#define IXGameImpl_XGameGetXboxTitleId(This,titleId) (This)->lpVtbl->XGameGetXboxTitleId(This,titleId)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameImpl_QueryInterface(IXGameImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameImpl_AddRef(IXGameImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameImpl_Release(IXGameImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameImpl methods ***/
static inline HRESULT IXGameImpl_XGameGetXboxTitleId(IXGameImpl* This,UINT32 *titleId) {
    return This->lpVtbl->XGameGetXboxTitleId(This,titleId);
}
#endif
#endif

#endif


#endif  /* __IXGameImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameImpl2 interface
 */
#ifndef __IXGameImpl2_INTERFACE_DEFINED__
#define __IXGameImpl2_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameImpl2, 0x50849859, 0x0ad8, 0x4f81, 0x80,0xe4, 0x5b,0xc7,0x86,0x26,0xf8,0x52);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("50849859-0ad8-4f81-80e4-5bc78626f852")
IXGameImpl2 : public IXGameImpl
{
    virtual void STDMETHODCALLTYPE XLaunchNewGame(
        const char *exePath,
        const char *args,
        XUserHandle defaultUser) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameImpl2, 0x50849859, 0x0ad8, 0x4f81, 0x80,0xe4, 0x5b,0xc7,0x86,0x26,0xf8,0x52)
#endif
#else
typedef struct IXGameImpl2Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameImpl2 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameImpl2 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameImpl2 *This);

    /*** IXGameImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameGetXboxTitleId)(
        IXGameImpl2 *This,
        UINT32 *titleId);

    /*** IXGameImpl2 methods ***/
    void (STDMETHODCALLTYPE *XLaunchNewGame)(
        IXGameImpl2 *This,
        const char *exePath,
        const char *args,
        XUserHandle defaultUser);

    END_INTERFACE
} IXGameImpl2Vtbl;

interface IXGameImpl2 {
    CONST_VTBL IXGameImpl2Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameImpl2_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameImpl2_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameImpl2_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameImpl methods ***/
#define IXGameImpl2_XGameGetXboxTitleId(This,titleId) (This)->lpVtbl->XGameGetXboxTitleId(This,titleId)
/*** IXGameImpl2 methods ***/
#define IXGameImpl2_XLaunchNewGame(This,exePath,args,defaultUser) (This)->lpVtbl->XLaunchNewGame(This,exePath,args,defaultUser)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameImpl2_QueryInterface(IXGameImpl2* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameImpl2_AddRef(IXGameImpl2* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameImpl2_Release(IXGameImpl2* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameImpl methods ***/
static inline HRESULT IXGameImpl2_XGameGetXboxTitleId(IXGameImpl2* This,UINT32 *titleId) {
    return This->lpVtbl->XGameGetXboxTitleId(This,titleId);
}
/*** IXGameImpl2 methods ***/
static inline void IXGameImpl2_XLaunchNewGame(IXGameImpl2* This,const char *exePath,const char *args,XUserHandle defaultUser) {
    This->lpVtbl->XLaunchNewGame(This,exePath,args,defaultUser);
}
#endif
#endif

#endif


#endif  /* __IXGameImpl2_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IXGameImpl3 interface
 */
#ifndef __IXGameImpl3_INTERFACE_DEFINED__
#define __IXGameImpl3_INTERFACE_DEFINED__

DEFINE_GUID(IID_IXGameImpl3, 0x2549f142, 0x6419, 0x4a06, 0x97,0xb5, 0x93,0x1a,0xab,0x7c,0x2f,0x34);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("2549f142-6419-4a06-97b5-931aab7c2f34")
IXGameImpl3 : public IXGameImpl2
{
    virtual HRESULT STDMETHODCALLTYPE XLaunchRestartOnCrash(
        const char *args,
        UINT32 reserved) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IXGameImpl3, 0x2549f142, 0x6419, 0x4a06, 0x97,0xb5, 0x93,0x1a,0xab,0x7c,0x2f,0x34)
#endif
#else
typedef struct IXGameImpl3Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IXGameImpl3 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IXGameImpl3 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IXGameImpl3 *This);

    /*** IXGameImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *XGameGetXboxTitleId)(
        IXGameImpl3 *This,
        UINT32 *titleId);

    /*** IXGameImpl2 methods ***/
    void (STDMETHODCALLTYPE *XLaunchNewGame)(
        IXGameImpl3 *This,
        const char *exePath,
        const char *args,
        XUserHandle defaultUser);

    /*** IXGameImpl3 methods ***/
    HRESULT (STDMETHODCALLTYPE *XLaunchRestartOnCrash)(
        IXGameImpl3 *This,
        const char *args,
        UINT32 reserved);

    END_INTERFACE
} IXGameImpl3Vtbl;

interface IXGameImpl3 {
    CONST_VTBL IXGameImpl3Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IXGameImpl3_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IXGameImpl3_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IXGameImpl3_Release(This) (This)->lpVtbl->Release(This)
/*** IXGameImpl methods ***/
#define IXGameImpl3_XGameGetXboxTitleId(This,titleId) (This)->lpVtbl->XGameGetXboxTitleId(This,titleId)
/*** IXGameImpl2 methods ***/
#define IXGameImpl3_XLaunchNewGame(This,exePath,args,defaultUser) (This)->lpVtbl->XLaunchNewGame(This,exePath,args,defaultUser)
/*** IXGameImpl3 methods ***/
#define IXGameImpl3_XLaunchRestartOnCrash(This,args,reserved) (This)->lpVtbl->XLaunchRestartOnCrash(This,args,reserved)
#else
/*** IUnknown methods ***/
static inline HRESULT IXGameImpl3_QueryInterface(IXGameImpl3* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG IXGameImpl3_AddRef(IXGameImpl3* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG IXGameImpl3_Release(IXGameImpl3* This) {
    return This->lpVtbl->Release(This);
}
/*** IXGameImpl methods ***/
static inline HRESULT IXGameImpl3_XGameGetXboxTitleId(IXGameImpl3* This,UINT32 *titleId) {
    return This->lpVtbl->XGameGetXboxTitleId(This,titleId);
}
/*** IXGameImpl2 methods ***/
static inline void IXGameImpl3_XLaunchNewGame(IXGameImpl3* This,const char *exePath,const char *args,XUserHandle defaultUser) {
    This->lpVtbl->XLaunchNewGame(This,exePath,args,defaultUser);
}
/*** IXGameImpl3 methods ***/
static inline HRESULT IXGameImpl3_XLaunchRestartOnCrash(IXGameImpl3* This,const char *args,UINT32 reserved) {
    return This->lpVtbl->XLaunchRestartOnCrash(This,args,reserved);
}
#endif
#endif

#endif


#endif  /* __IXGameImpl3_INTERFACE_DEFINED__ */

/*****************************************************************************
 * XGameImpl coclass
 */

DEFINE_GUID(CLSID_XGameImpl, 0x973a344e, 0x24bf, 0x4d0f, 0x84,0x57, 0x56,0xc5,0x34,0x89,0x2b,0x29);

#ifdef __cplusplus
class DECLSPEC_UUID("973a344e-24bf-4d0f-8457-56c534892b29") XGameImpl;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(XGameImpl, 0x973a344e, 0x24bf, 0x4d0f, 0x84,0x57, 0x56,0xc5,0x34,0x89,0x2b,0x29)
#endif
#endif

#endif
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __xgame_h__ */
